stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/shm
        - cp -frv ./include/shm $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libshm.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libshm.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_shm $UT_PATH

        - mkdir -p $BIN_PATH
        - cp -fv release/shmview $BIN_PATH

    only:
        - master

net:
    stage: trigger
    script:
        - curl -X POST -F token=b17588c70f782a54c7104e8159dddb -F ref=master $GITLAB_URL/api/v4/projects/12/trigger/pipeline
    only:
        - master
