#!/usr/bin/bash

MIN_COV="88%"
PROJECT_NAME=shm
BUILD_VERBOSE=OFF
source $TOOLCHAIN_PATH/build.in

if [[ $1 == "command" ]]; then
    echo "shm specific command"

else
     echo "ERROR: unknown command"
fi
